language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "8"
  - "9"
before_install:
  - npm i -g yarn
script:
  - yarn
  - yarn test
deploy:
  provider: npm
  email: macchenjl@foxmail.com
  skip_cleanup: true
  api_key:
    secure: W2gfmMDt3UI9ZJloIpstJaf9lrqAKGwqEeVc4+f9Xv4SzCKGwkWpaFyuFwF8kaN7wde32QOnGq2CreTUuXE3+Y4G+B0B0fJF2NETIofzuTwPFecgFg8gHffk1zN51vLuT5GygPWdcLRUwgGAslGJodHoDEvRkc4cxdml1OTS8tJYu4bbWSrmXqMDrm84p3Pto6lZkgpNC2i+cwh/1UMZvCXAdQXiqt2yLkgrrPmqHNUkbvDPQi9AIlLVlL8SQGfE1QaqVvJpvQ91sxZFQsOhr9LKpF5gC9Ig0FkGVoCbVzNE/KvvtTPjKUEbWy33ixT5VVEnxf+JX6JaJmjlm5qV4NaoDWKReieU016PREeBsPCkxUuRLryRxoDCCsqvONrPE2EOrqBQVrPXiaB7oBtEq+nWi7EJWdGbp5hO16EfqYSL11XQ+22tnq1Ztcn+TZyNToQ32oXa9Gy7tp2msrAAyxuU6vBzfairxBrlAQ4FLhLrktYGT1AZmgF+p/gedBY0AWzLrAXpk3Bfpf7XBp99y6BqfX8I+utgaGQHbH5XGgm8pYusHxZtVlrX7tHcoZTHpoH8BWouTlocPyPcDXssLUg4hI3xkVh4sJAhFFMr7hx2kUXZtphZXUUxxwauNG3Z780rIIPwLu/oVfANy5fCmnFfFDZ/m/XApU2M7ZXa/6I=
  on:
    tags: true
    repo: MZIchenjl/bodychecker
    all_branches: true
